name: CI

on: push

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.1', '7.2', '7.3', '7.4']
        name: PHP ${{ matrix.php-versions }}
        steps:
            - uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  ini-values: xdebug.mode=coverage
                  extensions: intl
                  tools: composer:v2

            - name: Check PHP Version
              run: php -v

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer update --no-progress

            - name: Run Phing
              run: composer run-script phing

    phpstan:
        runs-on: ubuntu-latest
        name: Static Analysis
        steps:
            - name: 📤 Checkout project
              uses: actions/checkout@v2

            - name: 🐘 Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  tools: composer:v2

            - name: 📦 Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer update --no-progress

            - name: 🔍 Analyse
              run: vendor/bin/phpstan analyse
